products = [
    {
        "id": 1,
        "name": "Wireless Bluetooth Headphones",
        "description": "High-quality over-ear headphones with noise cancellation and 20-hour battery life.",
        "price": 149.99,
        "category": "Electronics",
        "brand": "SoundWave",
        "image_url": "https://placehold.co/300x300?text=Wireless+Headphones",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-01",
        "stock": 50
    },
    {
        "id": 2,
        "name": "Cotton T-Shirt",
        "description": "Comfortable 100% cotton t-shirt available in multiple colors and sizes.",
        "price": 19.99,
        "category": "Clothing",
        "brand": "UrbanWear",
        "image_url": "https://placehold.co/300x300?text=Cotton+T-Shirt",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-02",
        "stock": 200
    },
    {
        "id": 3,
        "name": "Python Programming Book",
        "description": "Comprehensive guide to Python for beginners and advanced users.",
        "price": 34.50,
        "category": "Books",
        "brand": "TechPress",
        "image_url": "https://placehold.co/300x300?text=Python+Book",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-03",
        "stock": 100
    },
    {
        "id": 4,
        "name": "Running Shoes",
        "description": "Lightweight running shoes with cushioned soles for long-distance comfort.",
        "price": 89.99,
        "category": "Sports",
        "brand": "FitStep",
        "image_url": "https://placehold.co/300x300?text=Running+Shoes",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-04",
        "stock": 75
    },
    {
        "id": 5,
        "name": "Coffee Maker",
        "description": "Programmable drip coffee maker with 12-cup capacity and auto-shutoff.",
        "price": 79.99,
        "category": "Home & Kitchen",
        "brand": "BrewMaster",
        "image_url": "https://placehold.co/300x300?text=Coffee+Maker",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-05",
        "stock": 30
    },
    {
        "id": 6,
        "name": "Smartphone Case",
        "description": "Protective case for latest smartphones with shock absorption and slim design.",
        "price": 24.99,
        "category": "Electronics",
        "brand": "CaseGuard",
        "image_url": "https://placehold.co/300x300?text=Smartphone+Case",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-06",
        "stock": 150
    },
    {
        "id": 7,
        "name": "Yoga Mat",
        "description": "Non-slip yoga mat made from eco-friendly materials, 6mm thick.",
        "price": 39.99,
        "category": "Sports",
        "brand": "ZenFit",
        "image_url": "https://placehold.co/300x300?text=Yoga+Mat",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-07",
        "stock": 80
    },
    {
        "id": 8,
        "name": "Laptop Stand",
        "description": "Adjustable aluminum laptop stand for ergonomic typing and cooling.",
        "price": 49.99,
        "category": "Electronics",
        "brand": "ErgoTech",
        "image_url": "https://placehold.co/300x300?text=Laptop+Stand",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-08",
        "stock": 40
    },
    {
        "id": 9,
        "name": "Organic Tea Set",
        "description": "Assortment of organic teas with reusable infuser and storage tin.",
        "price": 29.99,
        "category": "Home & Kitchen",
        "brand": "HerbalBrew",
        "image_url": "https://placehold.co/300x300?text=Organic+Tea+Set",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-09",
        "stock": 60
    },
    {
        "id": 10,
        "name": "Wireless Mouse",
        "description": "Ergonomic wireless mouse with rechargeable battery and multi-device pairing.",
        "price": 34.99,
        "category": "Electronics",
        "brand": "ClickPro",
        "image_url": "https://placehold.co/300x300?text=Wireless+Mouse",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-01",
        "stock": 120
    },
    {
        "id": 11,
        "name": "Denim Jeans",
        "description": "Slim-fit denim jeans with stretch fabric for all-day comfort.",
        "price": 59.99,
        "category": "Clothing",
        "brand": "BlueDenim",
        "image_url": "https://placehold.co/300x300?text=Denim+Jeans",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-02",
        "stock": 90
    },
    {
        "id": 12,
        "name": "Fantasy Novel",
        "description": "Epic fantasy novel series starter with dragons and magic.",
        "price": 22.99,
        "category": "Books",
        "brand": "MythicTales",
        "image_url": "https://placehold.co/300x300?text=Fantasy+Novel",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-03",
        "stock": 150
    },
    {
        "id": 13,
        "name": "Dumbbell Set",
        "description": "Adjustable dumbbell set from 5-50 lbs for home workouts.",
        "price": 199.99,
        "category": "Sports",
        "brand": "PowerLift",
        "image_url": "https://placehold.co/300x300?text=Dumbbell+Set",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-04",
        "stock": 20
    },
    {
        "id": 14,
        "name": "Blender",
        "description": "High-speed blender for smoothies, soups, and nut butters.",
        "price": 99.99,
        "category": "Home & Kitchen",
        "brand": "BlendMaster",
        "image_url": "https://placehold.co/300x300?text=Blender",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-05",
        "stock": 45
    },
    {
        "id": 15,
        "name": "Screen Protector",
        "description": "Tempered glass screen protector for smartphones with anti-fingerprint coating.",
        "price": 14.99,
        "category": "Electronics",
        "brand": "ShieldTech",
        "image_url": "https://placehold.co/300x300?text=Screen+Protector",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-06",
        "stock": 300
    },
    {
        "id": 16,
        "name": "Backpack",
        "description": "Water-resistant backpack with multiple compartments for travel or daily use.",
        "price": 44.99,
        "category": "Clothing",
        "brand": "PackPro",
        "image_url": "https://placehold.co/300x300?text=Backpack",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-07",
        "stock": 70
    },
    {
        "id": 17,
        "name": "Cookbook",
        "description": "Healthy recipes cookbook focused on quick and easy meals.",
        "price": 27.99,
        "category": "Books",
        "brand": "QuickEats",
        "image_url": "https://placehold.co/300x300?text=Cookbook",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-08",
        "stock": 110
    },
    {
        "id": 18,
        "name": "Bicycle Helmet",
        "description": "Lightweight helmet with MIPS technology for safety and ventilation.",
        "price": 69.99,
        "category": "Sports",
        "brand": "SafeRide",
        "image_url": "https://placehold.co/300x300?text=Bicycle+Helmet",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-09",
        "stock": 55
    },
    {
        "id": 19,
        "name": "Toaster Oven",
        "description": "Compact toaster oven with convection baking and broiling functions.",
        "price": 54.99,
        "category": "Home & Kitchen",
        "brand": "ToastTech",
        "image_url": "https://placehold.co/300x300?text=Toaster+Oven",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-01",
        "stock": 35
    },
    {
        "id": 20,
        "name": "Power Bank",
        "description": "Portable power bank with 10000mAh capacity and fast charging.",
        "price": 39.99,
        "category": "Electronics",
        "brand": "ChargeUp",
        "image_url": "https://placehold.co/300x300?text=Power+Bank",
        "average_rating": 0.0,
        "num_reviews": 0,
        "created_at": "2025-10-02",
        "stock": 100
    }
]